#pragma config(Motor,  port2,           Right_Drive_F, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           Left_Drive_F,  tmotorVex393, openLoop)
#pragma config(Motor,  port5,           Left_Drive_B,  tmotorVex393, openLoop)
#pragma config(Motor,  port6,           Arm1,          tmotorVex393, openLoop)
#pragma config(Motor,  port7,           Arm2,          tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           Right_Drive_B, tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{
  int threshold = 40;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)
                        // feel free to change this to match your needs.

  while(1 == 1)
  {
    if(abs(vexRT[Ch3]) > threshold)         // If the left joystick is greater than or less than the threshold:
    {
      motor[Left_Drive_F]  = (vexRT[Ch3]);
      motor[Left_Drive_B] = (vexRT[Ch3]);// Left Joystick Y value / 2.
    }
    else                                    // If the left joystick is within the threshold:
    {
      motor[Left_Drive_F]  = 0;
      motor[Left_Drive_B]  = 0;           // Stop the left motor (cancel noise)
    }


    if(abs(vexRT[Ch2]) > threshold)         // If the right joystick is greater than or less than the threshold:
    {
       motor[Right_Drive_F]  = (vexRT[Ch2]);
      motor[Right_Drive_B] = (vexRT[Ch2]);   // Right Joystick Y value / 2.
    }
    else                                    // If the right joystick is within the threshold:
    {
      motor[Right_Drive_F] = 0;
      motor [Right_Drive_B] = 0;// Stop the right motor (cancel noise)
    }

    if(vexRT[Btn6U] ==1)
    {
    	motor[Arm1] = 100;
    	motor[Arm2] =100;
  	}
  	else if(vexRT[Btn6D] ==1)
  	{
  			motor[Arm1] = -100;
    	motor[Arm2] =-100;
  	}
  	else
  	{
  		motor[Arm1] = 0;
    	motor[Arm2] =0;
  	}
  }
}
