#pragma config(Sensor, in1,    potSelec,       sensorPotentiometer)
#pragma config(Motor,  port1,           rightArm2,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftFrontDrive, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           leftBackDrive, tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rightFrontDrive, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rightBackDrive, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm2,      tmotorVex393, openLoop)
#pragma config(Motor,  port7,           leftArm1,      tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightIntake,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           leftIntake,    tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightArm1,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int thresh = 25;

	while(1==1)
	{
		if(abs(vexRT [Ch3]) > thresh)
		{
			motor[leftBackDrive] = vexRT[Ch3];
			motor[leftFrontDrive] = vexRT[Ch3];
		}
		else
		{
			motor[leftBackDrive] = 0;
			motor[leftFrontDrive] = 0;
		}

		if(abs(vexRT [Ch2]) > thresh)
		{
			motor[rightBackDrive] = vexRT[Ch2];
			motor[rightFrontDrive] = vexRT[Ch2];
		}
		else
		{
			motor[rightBackDrive] = 0;
			motor[rightFrontDrive] = 0;
		}

		if(vexRT[Btn6U] == 1)
		{
			motor[leftArm1] = 63;
			motor[leftArm2] = 63;
			motor[rightArm1] = 63;
			motor[rightArm2] = 63;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[leftArm1] = -80;
			motor[leftArm2] = -80;
			motor[rightArm1] = -80;
			motor[rightArm2] = -80;
		}
		else
		{
			motor[leftArm1] = 0;
			motor[leftArm2] = 0;
			motor[rightArm1] = 0;
			motor[rightArm2] = 0;
		}

		if(vexRT[Btn8D] == 1){
			motor[leftIntake] = 70;
			motor[rightIntake] = 70;
		}
		else if (vexRT[Btn8U] == 1)
		{
			motor[leftIntake] = -70;
			motor[rightIntake] = -70;
		}
		else if (vexRT[Btn8R] == 1)
		{
			motor[leftIntake] = 0;
			motor[rightIntake] = 0;
		}


	}



}
