#pragma config(Sensor, in1,    pot,            sensorAnalog)
#pragma config(Sensor, in2,    xAxis,          sensorAccelerometer)
#pragma config(Sensor, in3,    yAxis,          sensorAccelerometer)
#pragma config(Sensor, in4,    zAxis,          sensorAccelerometer)
#pragma config(Sensor, in5,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in7,    leftClawPot,    sensorPotentiometer)
#pragma config(Sensor, in8,    rightClawPot,   sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393, PIDControl, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393, PIDControl, reversed, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port4,           rearRightMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rearLeftMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           leftArmMotor,  tmotorVex393, openLoop)
#pragma config(Motor,  port7,           rightArmMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftClawMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rightClawMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int nBiasValues[3];


#include "AutonomousFunctions.h"


task main()
{
	nBiasValues[0] = SensorValue[xAxis];
  nBiasValues[1] = SensorValue[yAxis];
  nBiasValues[2] = SensorValue[zAxis];
	float speed = 0;
	float height = 0;
	int accel = 0;
	while(1){
		accel = normalizeAccelerometer('y');
		if (abs(accel) >= 10){
			speed += accel*.02;
			ClearTimer(T1);
		}
		if (time1[T1] >= 40) speed = 0;
		height += speed;
		writeDebugStreamLine("%d %d %d", accel, speed, height);
		wait1Msec(5);

	}

}
