#pragma config(Sensor, in1,    pot,            sensorAnalog)
#pragma config(Sensor, in2,    xAxis,          sensorAccelerometer)
#pragma config(Sensor, in3,    yAxis,          sensorAccelerometer)
#pragma config(Sensor, in4,    zAxis,          sensorAccelerometer)
#pragma config(Sensor, in5,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in7,    leftClawPot,    sensorPotentiometer)
#pragma config(Sensor, in8,    rightClawPot,   sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393, PIDControl, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393, PIDControl, reversed, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port4,           rearRightMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rearLeftMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           leftArmMotor,  tmotorVex393, openLoop)
#pragma config(Motor,  port7,           rightArmMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftClawMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rightClawMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AutonomousFunctions.h"

task main()
{
	/*if (SensorValue[pot] >= 0 || SensorValue[pot] => 999)
	{

	}
	else if (SensorValue[pot] >= 1000 || SensorValue[pot] => 1999)
	{

	}
	else if (SensorValue[pot] >= 2000 || SensorValue[pot] > 2999)
	{

	}*/
	wait1Msec(500);
	//SensorBias[yAxis];
	while(1){

	/*if ((SensorValue[pot] >= 3000))
	{
		writeDebugStreamLine("One");
		wait10Msec(10);
	}
	else if (SensorValue[pot] >= 2000)
	{
		writeDebugStreamLine("Two");
		wait10Msec(10);
	}
	else if (SensorValue[pot] >= 1000)
	{
		writeDebugStreamLine("Three");
		wait10Msec(10);
	}
	else if (SensorValue[pot] >= 0)
	{
		writeDebugStreamLine("Four");
		wait10Msec(10);
	}
		writeDebugStreamLine("%d", SensorValue[pot]);
		wait10Msec(10);
	*/

		writeDebugStream("%f", SensorValue[xAxis]);
		writeDebugStream(" %f", SensorValue[yAxis]);
		writeDebugStreamLine(" %f", SensorValue[zAxis]);
		wait10Msec(5);
	}

}
