#pragma config(Sensor, in1,    pot,            sensorAnalog)
#pragma config(Sensor, in2,    xAxis,          sensorAccelerometer)
#pragma config(Sensor, in3,    yAxis,          sensorAccelerometer)
#pragma config(Sensor, in4,    zAxis,          sensorAccelerometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int normalizeAccelerometer(char axis)
{
	int nBiasValues[3];
  nBiasValues[0] = SensorValue[xAxis];
  nBiasValues[1] = SensorValue[yAxis];
  nBiasValues[2] = SensorValue[zAxis];

  switch (axis)
  {
  	case 'x':
  		return SensorValue[xAxis] - nBiasValues[0];
  	case 'y':
  		return SensorValue[xAxis] - nBiasValues[0];
  	case 'z':
  		return SensorValue[xAxis] - nBiasValues[0];
  }
  return 9001;

}

task main()
{
	/*if (SensorValue[pot] >= 0 || SensorValue[pot] => 999)
	{

	}
	else if (SensorValue[pot] >= 1000 || SensorValue[pot] => 1999)
	{

	}
	else if (SensorValue[pot] >= 2000 || SensorValue[pot] > 2999)
	{

	}*/
	wait1Msec(500);
	//SensorBias[yAxis];
	while(1){

	/*if ((SensorValue[pot] >= 3000))
	{
		writeDebugStreamLine("One");
		wait10Msec(10);
	}
	else if (SensorValue[pot] >= 2000)
	{
		writeDebugStreamLine("Two");
		wait10Msec(10);
	}
	else if (SensorValue[pot] >= 1000)
	{
		writeDebugStreamLine("Three");
		wait10Msec(10);
	}
	else if (SensorValue[pot] >= 0)
	{
		writeDebugStreamLine("Four");
		wait10Msec(10);
	}
		writeDebugStreamLine("%d", SensorValue[pot]);
		wait10Msec(10);
	*/

		writeDebugStream("%f", SensorValue[xAxis]);
		writeDebugStream(" %f", SensorValue[yAxis]);
		writeDebugStreamLine(" %f", SensorValue[zAxis]);
		wait10Msec(5);
	}


}
